name: Frontend CI

on:
  push:
    paths:
      - 'attus-frontend/**'
  pull_request:
    paths:
      - 'attus-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: attus-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --output-path=dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: dist/
