name: Frontend CI

on:
  push:
    branches:
      - main
      - pr-scripts-env
  pull_request:
    branches:
      - main
      - pr-scripts-env
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --output-path=dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: dist/
